// Copyright (c) 2026 Daniel Boles
// SPDX-License-Identifier: MIT
//
// Captures Wall Conductor reference output before its DSP is extracted, and
// checks against that capture afterwards. Same file both ways: with
// AF_CAPTURE it prints a header, without it compares.
#include "../src/plugin.hpp"
#ifndef AF_CAPTURE
#include "golden_wall_data.hpp"
#endif
#include <cmath>
#include <cstdio>

namespace {
enum { DENSITY_PARAM, PRESSURE_PARAM, WIDTH_PARAM, FEEDBACK_PARAM,
       RECOVERY_PARAM, COLLAPSE_PARAM };
enum { CH1_INPUT, CH2_INPUT, CH3_INPUT, CH4_INPUT };
enum { OUT_L_OUTPUT, OUT_R_OUTPUT };

struct S { const char* name; float density, pressure, width, feedback, recovery; bool collapse; };
const S SET[] = {
	{"quiet",        1.0f, 0.30f, 0.70f, 0.00f, 0.30f, false},
	{"pressured",    1.0f, 1.00f, 0.70f, 0.00f, 0.30f, false},
	{"fb_low",       1.0f, 0.30f, 0.70f, 0.40f, 0.30f, false},
	{"fb_past_edge", 1.0f, 0.25f, 0.70f, 1.00f, 0.30f, false},
	{"fb_max",       1.0f, 1.00f, 0.50f, 1.00f, 1.00f, false},
	{"collapsed",    1.0f, 0.50f, 0.70f, 0.30f, 0.50f, true},
	{"sparse",       0.3f, 0.50f, 0.00f, 0.20f, 0.30f, false},
};
const int WARM = 512, TAKE = 24;

float stim(int n, int c) {
	const float t = float(n) / 48000.f;
	return 2.f * std::sin(2.f * float(M_PI) * (110.f + 37.f * float(c)) * t);
}
}  // namespace

extern void init(rack::Plugin* p);

int main() {
	setvbuf(stdout, NULL, _IONBF, 0);
	rack::Plugin* pl = new rack::Plugin; pl->path = "."; pl->slug = "amplified-futures";
	init(pl);

#ifdef AF_CAPTURE
	std::printf("// Generated by tests/golden_wall.cpp -DAF_CAPTURE. Do not edit.\n");
	std::printf("#pragma once\nnamespace af { namespace goldenwall {\n");
	std::printf("struct Ref { const char* name; float d,p,w,f,r; bool collapse; float l[%d]; float rr[%d]; };\n", TAKE, TAKE);
	std::printf("static const int WARMUP=%d; static const int COUNT=%d;\n", WARM, TAKE);
	std::printf("static const Ref REFS[] = {\n");
#else
	int failures = 0; double worst = 0.0; const char* worstAt = "";
	const double TOL = 1e-3;
	std::printf("Wall Conductor against frozen reference, tolerance %.0e V\n\n", TOL);
#endif

	for (const S& s : SET) {
		rack::engine::Module* m = modelWallConductor->createModule();
		m->params[DENSITY_PARAM].setValue(s.density);
		m->params[PRESSURE_PARAM].setValue(s.pressure);
		m->params[WIDTH_PARAM].setValue(s.width);
		m->params[FEEDBACK_PARAM].setValue(s.feedback);
		m->params[RECOVERY_PARAM].setValue(s.recovery);
		m->params[COLLAPSE_PARAM].setValue(s.collapse ? 1.f : 0.f);
		// setChannels() is a no-op on a disconnected port: Rack deliberately
		// keeps channels at 0 so a port with no cable stays that way. Writing
		// the member directly is how a test fakes a patched cable.
		for (int i = CH1_INPUT; i <= CH4_INPUT; i++) m->inputs[i].channels = 1;

		rack::engine::Module::ProcessArgs a;
		a.sampleRate = 48000.f; a.sampleTime = 1.f / 48000.f; a.frame = 0;

#ifdef AF_CAPTURE
		std::printf("  {\"%s\", %.4ff,%.4ff,%.4ff,%.4ff,%.4ff, %s, {", s.name,
		            s.density, s.pressure, s.width, s.feedback, s.recovery,
		            s.collapse ? "true" : "false");
		float L[TAKE], R[TAKE];
#else
		double mine = 0.0;
#endif
		for (int n = 0; n < WARM + TAKE; n++) {
			for (int i = 0; i < 4; i++) m->inputs[CH1_INPUT + i].setVoltage(stim(n, i), 0);
			m->process(a); a.frame++;
			if (n < WARM) continue;
			const float ol = m->outputs[OUT_L_OUTPUT].getVoltage(0);
			const float orr = m->outputs[OUT_R_OUTPUT].getVoltage(0);
#ifdef AF_CAPTURE
			L[n - WARM] = ol; R[n - WARM] = orr;
#else
			const af::goldenwall::Ref& ref = af::goldenwall::REFS[&s - SET];
			const double dl = std::fabs(double(ol) - double(ref.l[n - WARM]));
			const double dr = std::fabs(double(orr) - double(ref.rr[n - WARM]));
			if (dl > mine) mine = dl;
			if (dr > mine) mine = dr;
#endif
		}
		delete m;
#ifdef AF_CAPTURE
		for (int i = 0; i < TAKE; i++) std::printf("%.9ef,", L[i]);
		std::printf("}, {");
		for (int i = 0; i < TAKE; i++) std::printf("%.9ef,", R[i]);
		std::printf("}},\n");
#else
		if (mine > worst) { worst = mine; worstAt = s.name; }
		if (mine > TOL) failures++;
		std::printf("  %-14s worst |d| %.3g  %s\n", s.name, mine, mine <= TOL ? "" : "  FAIL");
#endif
	}

#ifdef AF_CAPTURE
	std::printf("};\nstatic const int REF_COUNT=%d;\n}}\n", int(sizeof(SET)/sizeof(SET[0])));
	return 0;
#else
	std::printf("\nworst overall %.3g V, in %s\n%d references, %d failure(s)\n",
	            worst, worstAt, int(sizeof(SET)/sizeof(SET[0])), failures);
	if (!failures) std::printf("the rewired module still sounds like the reference\n");
	return failures ? 1 : 0;
#endif
}
