// Copyright (c) 2026 Daniel Boles
// SPDX-License-Identifier: MIT
//
// DroneClone reference output. With AF_CAPTURE it writes the header, without
// it compares against it. Captured BEFORE the DSP is extracted, so the
// extraction has something independent to be checked against.
#include "../src/plugin.hpp"
#ifndef AF_CAPTURE
#include "golden_drone_data.hpp"
#endif
#include <cmath>
#include <cstdio>

namespace {
enum { FUNDAMENTAL_PARAM, SPREAD_PARAM, MASS_PARAM, TENSION_PARAM, WEIGHT_PARAM,
       SHIMMER_PARAM, JAWARI_PARAM, DRIFT_PARAM, DECAY_PARAM, CHOKE_AMT_PARAM,
       CHOKE_PARAM };
enum { VOCT_INPUT };
enum { OUT_OUTPUT };

struct S { const char* name; float fund, spread, mass, tension, weight,
                              shimmer, jawari, drift; float voct; };
const S SET[] = {
	{"bare",      0.f, 0.30f, 1.00f, 0.00f, 0.00f, 0.00f, 0.00f, 0.00f,  0.f},
	{"tension",   0.f, 0.30f, 1.00f, 1.00f, 0.00f, 0.00f, 0.00f, 0.00f,  0.f},
	{"shimmer",   0.f, 0.30f, 1.00f, 0.00f, 0.00f, 1.00f, 0.00f, 0.00f,  0.f},
	{"jawari",    0.f, 0.30f, 1.00f, 0.00f, 0.00f, 0.00f, 1.00f, 0.00f,  0.f},
	{"weight",    0.f, 0.30f, 1.00f, 0.00f, 1.00f, 0.00f, 0.00f, 0.00f, -1.f},
	{"drift",     0.f, 0.50f, 1.00f, 0.00f, 0.00f, 0.00f, 0.00f, 1.00f,  0.f},
	{"everything",1.f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, -2.f},
	{"partial",   0.f, 0.20f, 0.44f, 0.50f, 0.00f, 0.00f, 0.00f, 0.00f,  1.f},
};
const int WARM = 4096, TAKE = 24;
}  // namespace

extern void init(rack::Plugin* p);

int main() {
	setvbuf(stdout, NULL, _IONBF, 0);
	rack::Plugin* pl = new rack::Plugin; pl->path = "."; pl->slug = "amplified-futures";
	init(pl);

#ifdef AF_CAPTURE
	std::printf("// Generated by tests/golden_drone.cpp -DAF_CAPTURE. Do not edit.\n");
	std::printf("#pragma once\nnamespace af { namespace goldendrone {\n");
	std::printf("struct Ref { const char* name; float s[%d]; };\n", TAKE);
	std::printf("static const int WARMUP=%d; static const int COUNT=%d;\n", WARM, TAKE);
	std::printf("static const Ref REFS[] = {\n");
#else
	int failures = 0; double worst = 0.0; const char* worstAt = "";
	const double TOL = 1e-3;
	std::printf("DroneClone against frozen reference, tolerance %.0e V\n\n", TOL);
#endif

	for (const S& s : SET) {
		rack::engine::Module* m = modelDroneClone->createModule();
		m->params[FUNDAMENTAL_PARAM].setValue(s.fund);
		m->params[SPREAD_PARAM].setValue(s.spread);
		m->params[MASS_PARAM].setValue(s.mass);
		m->params[TENSION_PARAM].setValue(s.tension);
		m->params[WEIGHT_PARAM].setValue(s.weight);
		m->params[SHIMMER_PARAM].setValue(s.shimmer);
		m->params[JAWARI_PARAM].setValue(s.jawari);
		m->params[DRIFT_PARAM].setValue(s.drift);
		m->inputs[VOCT_INPUT].channels = 1;
		m->inputs[VOCT_INPUT].setVoltage(s.voct, 0);

		rack::engine::Module::ProcessArgs a;
		a.sampleRate = 48000.f; a.sampleTime = 1.f / 48000.f; a.frame = 0;

#ifdef AF_CAPTURE
		std::printf("  {\"%s\", {", s.name);
#else
		double mine = 0.0;
		const af::goldendrone::Ref& ref = af::goldendrone::REFS[&s - SET];
#endif
		for (int n = 0; n < WARM + TAKE; n++) {
			m->process(a); a.frame++;
			if (n < WARM) continue;
			const float v = m->outputs[OUT_OUTPUT].getVoltage(0);
#ifdef AF_CAPTURE
			std::printf("%.9ef,", v);
#else
			const double d = std::fabs(double(v) - double(ref.s[n - WARM]));
			if (d > mine) mine = d;
#endif
		}
		delete m;
#ifdef AF_CAPTURE
		std::printf("}},\n");
#else
		if (mine > worst) { worst = mine; worstAt = s.name; }
		if (mine > TOL) failures++;
		std::printf("  %-12s worst |d| %.3g  %s\n", s.name, mine, mine <= TOL ? "" : "  FAIL");
#endif
	}

#ifdef AF_CAPTURE
	std::printf("};\nstatic const int REF_COUNT=%d;\n}}\n", int(sizeof(SET)/sizeof(SET[0])));
#else
	std::printf("\nworst overall %.3g V, in %s\n%d references, %d failure(s)\n",
	            worst, worstAt, int(sizeof(SET)/sizeof(SET[0])), failures);
	if (!failures) std::printf("the rewired module still sounds like the reference\n");
	return failures ? 1 : 0;
#endif
	return 0;
}
